//***********************************************************************/
//    Author                    : tywind
//    Original Date             : oct 11 2014
//    Module Name               : BIOSVGA.H
//    Module Funciton           : 
//    Lines number              :
//***********************************************************************/

#ifndef __BIOSVGA_H__
#define __BIOSVGA_H__


BOOL BiosVgaDriverEntry(__DISPALY_OBJECT* lpDriverObject);

#endif  //__BIOSVGA_H__
